version: "3"
services:
  fire-scaffold:
    build: ./
    ports:
      - "8880:8080"
    links:
      - "mysql"
      - "redis"
    tty: true
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - /home/code/data/golang-mysql/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
  redis:
    image: redis
    ports:
      - "6379:6379"
